apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-deluge
  namespace: media
spec:
  provider: vault
  secretObjects:
    - secretName: vault-openvpn-secret
      type: Opaque
      data:
        - objectName: username # References pia-username below
          key: username # Key within k8s secret for this value
        - objectName: password
          key: password
        - objectName: region
          key: region
        - objectName: provider
          key: provider
  parameters:
    vaultAddress: "https://vault.apps.internal:8200"
    vaultNamespace: "engineering"
    vaultSkipTLSVerify: "true"
    roleName: "deluge"
    objects: |
      - objectName: "username"
        secretPath: "pia-prod/data/account"
        secretKey: "username"
      - objectName: "password"
        secretPath: "pia-prod/data/account"
        secretKey: "password"
      - objectName: "region"
        secretPath: "pia-prod/data/account"
        secretKey: "region"
      - objectName: "provider"
        secretPath: "pia-prod/data/account"
        secretKey: "provider"