---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-certificate
  namespace: longhorn-system
spec:
  secretName: longhorn-certificate-tls
  issuerRef: 
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
  commonName: "longhorn.dev.local"
  dnsNames:
    - "longhorn.dev.local"
  isCA: false
  duration: 2160h # 90d
  renewBefore: 350h # 15d