apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: deluge
  namespace: media
spec:
  provider: vault
  secretObjects:
    - secretName: pia-credentials
      type: Opaque
      data:
        - objectName: username # References username below
          key: username # Key within k8s secret for this value
        - objectName: password
          key: password
        - objectName: region
          key: region
        - objectName: provider
          key: provider
  parameters:
    vaultAddress: "https://vault.service.blizzard.consul:8200"
    vaultSkipTLSVerify: "true"
    roleName: "deluge"
    objects: |
      - objectName: "username"
        secretPath: "kv-v2/data/privateinternetaccess"
        secretKey: "username"
      - objectName: "password"
        secretPath: "kv-v2/data/privateinternetaccess"
        secretKey: "password"
      - objectName: "region"
        secretPath: "kv-v2/data/privateinternetaccess"
        secretKey: "region"
      - objectName: "provider"
        secretPath: "kv-v2/data/privateinternetaccess"
        secretKey: "provider"