---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: https://vault.apps.blizzard.internal:8200
      caProvider:
        name: blizzard-ca
        type: ConfigMap
        key: ca-certificate
        namespace: kube-system
      auth:
        kubernetes:
          mountPath: kubernetes_home
          role: external-secrets-operator
          serviceAccountRef:
            name: external-secrets-operator
            namespace: kube-system
