---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
  namespace: media
spec:
  template:
    spec:
      containers:
      - name: plex
        volumeMounts:
          - name: config
            mountPath: /config
          - name: transcode
            mountPath: /transcode
          - name: data
            mountPath: /data
      volumes:
      - name: data
        nfs:
          server: blizzardnas.blizzard.internal
          path: /volume1/array
      - name: transcode
        emptyDir:
          sizeLimit: 25Gi
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 50Gi
