---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
  namespace: media
spec:
  template:
    spec:
      containers:
      - name: plex
        env:
          - name: PLEX_CLAIM
            valueFrom:
              secretKeyRef:
                name: plex-credentials
                key: claim
        volumeMounts:
          - name: plex-credentials
            mountPath: '/mnt/secrets-store'
            readOnly: true
          - name: config
            mountPath: /config
          - name: transcode
            mountPath: /transcode
          - name: data
            mountPath: /data
      volumes:
      - name: data
        nfs:
          server: blizzardnas.blizzard.internal
          path: /volume1/array
      - name: plex-credentials
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: plex
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: transcode
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 10Gi