---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: plex
  namespace: media
spec:
  provider: vault
  secretObjects:
    - secretName: plex-credentials
      type: Opaque
      data:
        - objectName: claim # References username below
          key: claim # Key within k8s secret for this value
  parameters:
    vaultAddress: "https://vault.apps.blizzard.internal:8200"
    vaultSkipTLSVerify: "true"
    vaultKubernetesMountPath: "kubernetes_home"
    roleName: "plex"
    objects: |
      - objectName: "claim"
        secretPath: "prod-static/data/plex"
        secretKey: "claim"