---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
bases:
  - ../../../base/media/unpackerr
patchesStrategicMerge:
  - patch.yaml
resources:
  - secretproviderclass.yaml