---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: unpackerr
  namespace: media
spec:
  provider: vault
  secretObjects:
    - secretName: sonarr-api-key
      type: Opaque
      data:
        - objectName: api_key # References api_key below
          key: api_key # Key within k8s secret for this value
  parameters:
    vaultAddress: "https://vault.apps.blizzard.internal:8200"
    vaultSkipTLSVerify: "true"
    vaultKubernetesMountPath: "kubernetes_home"
    roleName: "unpackerr"
    objects: |
      - objectName: "api_key"
        secretPath: "prod-static/data/sonarr"
        secretKey: "api_key"