---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
spec:
  selector:
    app: qbittorrent
  ports:
    - name: qbittorrent
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  clusterIP: None