---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-certificate
  namespace: longhorn-system
spec:
  secretName: longhorn-certificate-tls
  issuerRef: 
    kind: ClusterIssuer
    name: vault-cluster-issuer
  commonName: "longhorn.apps.blizzard.internal"
  dnsNames:
    - "longhorn.apps.blizzard.internal"
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  duration: 2160h # 90d
  renewBefore: 350h # 15d