---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-webhook-url
  namespace: longhorn-system
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: slack-webhook-url
  data:
  - secretKey: webhook-url
    remoteRef:
      key: prod-static/slack
      property: webhook-url