---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/longhorn
  - certificate.yaml
  - release.yaml
  - servicemonitor.yaml
  - externalsecret.yaml # needed before alertmanagerconfig
  - prometheusrule.yaml
  - alertmanagerconfig.yaml