---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  - externalsecret.yaml
  - alertmanagerconfig.yaml
  - deluge
  - sonarr
  - radarr
  - prowlarr
  # - plex