---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: postgresql
spec:
  serviceName: postgresql
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          volumeMounts:
            - name: postgresql-disk
              mountPath: /data
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: psql
            - name: POSTGRES_INITDB_ARGS
              value: -A md5
      volumes:
        - name: psql-creds
          secret:
            secretName: psql-creds
  volumeClaimTemplates:
    - metadata:
        name: postgresql-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 500Mi