---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media
spec:
  selector:
    app: sonarr
  ports:
    - name: sonarr
      protocol: TCP
      port: 8989
      targetPort: 8989
  type: ClusterIP
  clusterIP: None