---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media
spec:
  selector:
    app: prowlarr
  ports:
    - name: prowlarr
      protocol: TCP
      port: 8989
      targetPort: 8989
  type: ClusterIP
  clusterIP: None