---
- name: Retrieve Secrets Store CSI driver manifests
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "./{{ item | basename }}"
  with_items:
    - https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/v{{ secrets_store_csi_driver_version }}/deploy/rbac-secretproviderclass.yaml
    - https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/v{{ secrets_store_csi_driver_version }}/deploy/rbac-secretprovidersyncing.yaml
    - https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/v{{ secrets_store_csi_driver_version }}/deploy/rbac-secretproviderrotation.yaml
    - https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/v{{ secrets_store_csi_driver_version }}/deploy/csidriver.yaml
    - https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/v{{ secrets_store_csi_driver_version }}/deploy/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
    - https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/v{{ secrets_store_csi_driver_version }}/deploy/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
    - https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/v{{ secrets_store_csi_driver_version }}/deploy/secrets-store-csi-driver.yaml

- name: Install Secrets Store CSI driver
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
    kubeconfig: "{{ playbook_dir }}/kubeconfig"
  with_items:
    - rbac-secretproviderclass.yaml
    - rbac-secretprovidersyncing.yaml
    - rbac-secretproviderrotation.yaml
    - csidriver.yaml
    - secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
    - secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
    - secrets-store-csi-driver.yaml

- name: Remove local MetalLB manifests
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - rbac-secretproviderclass.yaml
    - rbac-secretprovidersyncing.yaml
    - rbac-secretproviderrotation.yaml
    - csidriver.yaml
    - secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
    - secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml
    - secrets-store-csi-driver.yaml