---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent-certificate
  namespace: media
spec:
  secretName: qbittorrent-certificate-tls
  issuerRef: 
    kind: ClusterIssuer
    name: vault-cluster-issuer
  commonName: "qbittorrent.apps.blizzard.internal"
  dnsNames:
    - "qbittorrent.apps.blizzard.internal"
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  duration: 2160h # 90d
  renewBefore: 350h # 15d