---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: qbittorrent
  namespace: media
spec:
  provider: vault
  secretObjects:
    - secretName: vpn-credentials
      type: Opaque
      data:
        - objectName: username # References username below
          key: username # Key within k8s secret for this value
        - objectName: password
          key: password
        - objectName: region
          key: region
        - objectName: provider
          key: provider
  parameters:
    vaultAddress: "https://vault.apps.blizzard.internal:8200"
    vaultSkipTLSVerify: "true"
    vaultKubernetesMountPath: "kubernetes_home"
    roleName: "qbittorrent"
    objects: |
      - objectName: "username"
        secretPath: "prod-static/data/vpn-account"
        secretKey: "username"
      - objectName: "password"
        secretPath: "prod-static/data/vpn-account"
        secretKey: "password"
      - objectName: "region"
        secretPath: "prod-static/data/vpn-account"
        secretKey: "region"
      - objectName: "provider"
        secretPath: "prod-static/data/vpn-account"
        secretKey: "provider"