---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: deluge
  namespace: media
spec:
  serviceName: deluge
  selector:
    matchLabels:
      app: deluge
      group: media
  template:
    metadata:
      labels:
        app: deluge
        group: media
    spec:
      serviceAccountName: deluge
      containers:
      - name: deluge
        image: linuxserver/deluge:latest
        env:
          - name: PUID
            value: '1027'
          - name: PGID
            value: '100'
          - name: TZ
            value: 'America/Toronto'
        readinessProbe:
          tcpSocket:
            port: 8112
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
          - name: deluge
            containerPort: 8112