---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-cluster-issuer
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-cluster-issuer-token-reviewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-cluster-issuer
  namespace: cert-manager 
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-cluster-issuer-token
  namespace: cert-manager
  annotations:
    kubernetes.io/service-account.name: "vault-cluster-issuer"
type: kubernetes.io/service-account-token
data: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-cluster-issuer
spec:
  vault:
    path: prod-pki/sign/apps-blizzard-internal
    server: https://vault.apps.blizzard.internal:8200
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ5RENDQXR5Z0F3SUJBZ0lVZVRVU0RJb3FtcSt1THZGWGdWZFcrYzFtK213d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2daRXhDekFKQmdOVkJBWVRBa05CTVJBd0RnWURWUVFJRXdkUGJuUmhjbWx2TVJBd0RnWURWUVFIRXdkVQpiM0p2Ym5Sdk1SWXdGQVlEVlFRS0V3MUNiR2w2ZW1GeVpDQk1ZV0p6TVNJd0lBWURWUVFMRXhsQ2JHbDZlbUZ5ClpDQkpiblJsY201aGJDQlNiMjkwSUVOQk1TSXdJQVlEVlFRREV4bENiR2w2ZW1GeVpDQkpiblJsY201aGJDQlMKYjI5MElFTkJNQjRYRFRJek1ESXlOVEl5TWpnd01Gb1hEVEk0TURJeU5ESXlNamd3TUZvd2daRXhDekFKQmdOVgpCQVlUQWtOQk1SQXdEZ1lEVlFRSUV3ZFBiblJoY21sdk1SQXdEZ1lEVlFRSEV3ZFViM0p2Ym5Sdk1SWXdGQVlEClZRUUtFdzFDYkdsNmVtRnlaQ0JNWVdKek1TSXdJQVlEVlFRTEV4bENiR2w2ZW1GeVpDQkpiblJsY201aGJDQlMKYjI5MElFTkJNU0l3SUFZRFZRUURFeGxDYkdsNmVtRnlaQ0JKYm5SbGNtNWhiQ0JTYjI5MElFTkJNSUlCSWpBTgpCZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1b2JueUx6UmRkWUVxSUJJVkMvaEpHaEl1MDRNClZoMmJsMS9pWmxOSWpiWkJUa2ZLVm9VV05paTNEWlg4bmV6NityRkxsL05sS2Ztdm1FNzlwRnNQQXQyOWxETTIKV1JhNFdYRndOb1AxUVZTOU1hMTF2aFp6T08xdEtaOWRsMnFPNTNtbENaN2FUdmJiYVF2U2YyKzNUWHk4ajFmMwp4eXZ5QnJpWkFZek9KRjcrYnBWcXIxdWdwVGt1VXNnUTFoT2FuekZMRWcrSzcyQmZ3ZjJoSUZTOTQrM3ZQaTZUCi9LS1BZVXo1dVRRay9JK01GNkNQaXEzTnQ4KytOLzF5Q3hqNGlBYlZrYzRENVNCVXkwbHdIeUZVVGhUci9aWkEKallUa3ZMa1hmSEFmYlFYdGlvKzZDR0Z3U1p1V3JtNE53eXRzMGxJRmJNLytncTgyUVFkR1hvd1ZjUUlEQVFBQgpvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBUVl3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVClRxZVZuclh6aW5ZVHZlUVVlZ2N6cFcwOS9yOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRzRNSFFaRm5CYmkKblJwTmhqajhQZG4wVUhGTUx5RnQ1N1RZYkdSRHpJMlZpUHYwQ1ZxcTA4ZG9CVmQxUG16c0crODUyWlBLZHVRdwpTeHMvNmJ1azhndWNVSS9CL3JjL29mYmgycnBOZ0RKR0U3cnc4M3dMcVc5a3FUMjdZRkVURDMxL0VTdHMvK0NIClFyT0NQVUl3R2QyZllWQmNCTVIzOWlCOEZSUmluMjJFamYvdmVRSXJzYXNQS1NTTlRkRG1iQ2UzQ1FXNTNYZW4KSFJHVlRoVk1qR1BDZTFFQWhqcjRmOFhZa2d5VGtMcWs1V0tHbHJLUEVISkhjYlJlaDhMaDBDaHBHMTdnQjFzMQovT3F2b3EzRWZwb3lJNi9pMnhDdXZqbzMzR0MxMTkxTEwwZ3h6NlBCMUhydWRCelBMYWNnSnBmZnZhNGtCdVJFClRSVUppYjNpUEFZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    auth:
      kubernetes:
        role: cert-manager
        mountPath: /v1/auth/kubernetes_home
        secretRef:
          name: vault-cluster-issuer-token
          key: token