---
- name: Deploy HashiCorp Vault
  hosts: vault
  become: true
  roles:
    - ansible-role-vault

- name: Additional Vault configurations
  hosts: vault
  become: true
  tasks:
    - name: Setup logrotate for Vault Audit
      ansible.builtin.copy:
        content: |
          /opt/vault/vault_audit.log {
            daily
            rotate 3
            size 10M
            compress
            delaycompress
          }
        dest: /etc/logrotate.d/vault.conf