---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
bases:
  - ../../../base/media/radarr
patchesStrategicMerge:
  - patch.yaml
resources:
  - certificate.yaml
  - ingress.yaml