---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system
spec:
  dependsOn:
    - name: core
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/flux/crds/home
  prune: true