---
- name: Install codeserver package
  ansible.builtin.apt:
    deb: "https://github.com/coder/code-server/releases/download/v{{ code_server_version }}/code-server_{{ code_server_version }}_{{ install_architecture }}.deb"
  notify: Restart code-server

- name: Start and enable code-server service
  ansible.builtin.systemd:
    name: "code-server@{{ code_server_user }}"
    state: started
    enabled: true