---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plex
  namespace: media
  labels:
    app: plex
    group: media
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: plex-tokenreviewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: plex
  namespace: media