---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
spec:
  selector:
    app: plex
  ports:
    - name: plex
      protocol: TCP
      port: 32400
      targetPort: 32400
  type: ClusterIP
  clusterIP: None