---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
spec:
  selector:
    app: plex
  ports:
    - name: plex-server
      protocol: TCP
      port: 32400
      targetPort: 32400
    - name: plex-companion
      protocol: TCP
      port: 8324
      targetPort: 8324
    - name: plex-dlna-server-tcp
      protocol: TCP
      port: 32469
      targetPort: 32469
    - name: plex-dlna-server-udp
      protocol: UDP
      port: 1900
      targetPort: 1900
    - name: plex-bonjour
      protocol: UDP
      port: 5353
      targetPort: 5353
    - name: plex-gdp-a
      protocol: UDP
      port: 32410
      targetPort: 32410
    - name: plex-gdp-b
      protocol: UDP
      port: 32412
      targetPort: 32412
    - name: plex-gdp-c
      protocol: UDP
      port: 32413
      targetPort: 32413
    - name: plex-gdp-d
      protocol: UDP
      port: 32414
      targetPort: 32414  
  type: ClusterIP
  clusterIP: None