---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
  namespace: media
spec:
  serviceName: plex
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: plex
      group: media
  template:
    metadata:
      labels:
        app: plex
        group: media
    spec:
      serviceAccountName: plex
      containers:
        - name: plex
          image: plexinc/pms-docker:1.29.2.6364-6d72b0cf6
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: TZ
              value: America/Toronto
            - name: ADVERTISE_IP
              value: "https://$(HOST_IP):32400"
          readinessProbe:
            tcpSocket:
              port: 32400
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - name: server
              containerPort: 32400
              hostPort: 32400
            - name: companion
              containerPort: 8324
              hostPort: 8324
            - name: dlna-tcp
              containerPort: 32469
              hostPort: 32469
            - name: dlna-udp
              containerPort: 1900
              hostPort: 1900
            - name: bonjour
              containerPort: 5353
              hostPort: 5353
            - name: gdp-a
              containerPort: 32410
              hostPort: 32410
            - name: gdp-b
              containerPort: 32412
              hostPort: 32412
            - name: gdp-c
              containerPort: 32413
              hostPort: 32413
            - name: gdp-d
              containerPort: 32414
              hostPort: 32414
