---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
  namespace: media
spec:
  serviceName: plex
  selector:
    matchLabels:
      app: plex
      group: media
  template:
    metadata:
      labels:
        app: plex
        group: media
    spec:
      serviceAccountName: plex
      containers:
        - name: plex
          image: plexinc/pms-docker:1.28.2.6151-914ddd2b3
          env:
            - name: TZ
              value: 'America/Toronto'
          readinessProbe:
            tcpSocket:
              port: 32400
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - name: plex
              containerPort: 32400
              hostPort: 32400